% preprocess_data.m
%
% This script performs preprocessing on raw Raman spectral data, including
% wavenumber selection, fluorescence background removal, spike removal,
% reference assignment, and Savitzky-Golay derivatization.
% The processed data is saved as a .mat file for further analysis.
%
% INPUT: Loads data/Raman/raw_data/raw_data_imported.mat, generated by
%        code/Raman/read_raw_data.m.
%
% OUTPUT: Saves processed spectra (X_proc), processed wavenumbers (wn_proc),
%         sample IDs (ID_proc), reference values (Y_proc), and labels (Ylab)
%         in 'processed_data.mat'
%
% USAGE: From the project root, run('code/Raman/preprocess_data.m').

clear; close all; clc;
scriptDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(scriptDir));
if ~exist(fullfile(projectRoot, 'code'), 'dir') || ~exist(fullfile(projectRoot, 'data'), 'dir')
    projectRoot = pwd;
end
if ~exist(fullfile(projectRoot, 'code'), 'dir') || ~exist(fullfile(projectRoot, 'data'), 'dir')
    error('Project root could not be resolved. Set the MATLAB current folder to the project root and run the script again.');
end

% --- Load imported raw data ---
load(fullfile(projectRoot, 'data', 'Raman', 'raw_data', 'raw_data_imported.mat')); % contains X, wn, ID, ref_values, ref_varID

% --- 1. Wavenumber Selection (Truncate to [400, 1500] cm^-1) ---
[~,a] = min(abs(wn - 400));
[~,b] = min(abs(wn - 1500));
wn_proc = wn(a:b);       % keep only selected wavenumber range
X_proc = X(:, a:b);
clear a b

% --- 2. Remove Fluorescence Background (Asymmetric Least Squares) ---
lambda_x = 1e6;    % Smoothing parameter %1e6
p_x     = 0.001;   % Asymmetry parameter %0.001
d_x     = 3;       % Order of difference penalty % 3

addpath(fullfile(projectRoot, 'code', 'functions'));
for i = 1:size(X_proc,1)
    baseline = asysm(X_proc(i,:)', lambda_x, p_x, d_x);   % custom function
%     plot(wn_proc,X_proc(i,:)); hold on
%     plot(wn_proc,baseline); hold off;
%     pause
    X_proc(i,:) = X_proc(i,:) - baseline';                % subtract baseline
end
clear lambda_x p_x d_x i baseline

% --- 3. Remove Spikes ---
X_proc = remove_spikes(X_proc, ID);

% --- 4. Retain observation-level spectra ---
ID_proc = ID;
N = size(X_proc,1);

% --- 5. Assign Reference Values (Y) by Sample ID ---
Y_proc = nan(N, size(ref_values,2)); % [samples x analytes]
for i = 1:size(ref_values,1)
    idx = ID_proc == i;
    Y_proc(idx,:) = repmat(ref_values(i,:), sum(idx), 1);
end
Ylab = ref_varID;
clear i idx ref_values ref_varID

% --- 6. Savitzky-Golay Derivative Filtering ---
pol = 2;         % Polynomial order %2
win = 7;         % Window size % 7
der = 2;         % Derivative order %2

I = floor(win/2);
X_proc = SavitzkyGolay(X_proc, pol, win, der);    % custom S-Golay function
X_proc = X_proc(:, I+1:end-I);                    % trim edges
wn_proc = wn_proc(I+1:end-I);                     % update wavenumber range
clear pol win der I

% --- 7. Save Processed Data ---
% Use .mat file for full MATLAB compatibility and easy sharing
outdir = fullfile(projectRoot, 'data', 'Raman', 'processed_data');
if ~exist(outdir, 'dir')
    mkdir(outdir);
end
save(fullfile(outdir, 'processed_data.mat'), 'X_proc', 'wn_proc', 'ID_proc', 'Y_proc', 'Ylab');
disp('Processed data saved to processed_data.mat');

% Export CSV copies for non-MATLAB use
writematrix(X_proc, fullfile(outdir, 'processed_spectra.csv'));
writematrix(wn_proc, fullfile(outdir, 'processed_wavenumbers.csv'));
writematrix(ID_proc, fullfile(outdir, 'processed_ID.csv'));
writematrix(Y_proc, fullfile(outdir, 'processed_reference.csv'));

% --- Script completed ---
disp(['Preprocessing completed. Final dataset: ' num2str(size(X_proc,1)) ' samples x ' num2str(size(X_proc,2)) ' spectral vars.']);

